### ISSUE TITLE
4.2 regression checklist

### ISSUE THREAD

**Issue by clefebvre** [linuxmint/alpha-testing#16]
- [x] Restoring maximized slack from systray leads to non-maximized slack, with glitching
- [x] Artefacts in window list
- [x] Crash in meta_window_should_unredirect (introduced by https://github.com/linuxmint/muffin/commit/1d01e839d55239e5cad0a8498017b25079474c61)
- [ ] Glitch when choosing Fly Down in window effects dialog (introduced in 4.0-maintenance by https://github.com/linuxmint/muffin/commit/8ce454463fc067cf1f95417f791166a64cc0bb52)
- [x] Stuck tooltips around systray https://github.com/linuxmint/alpha-testing/issues/15 (introduced by https://github.com/linuxmint/cinnamon/commit/74d14ea9cbb01849d46cda8673d668a6861e29b4)
- [x] Stuck notifications
- [x] Freeze when closing a fullscreen unredirect window (@itzexor mpv case)
- [x] Freeze after entering password in screensaver (see below) (introduced by https://github.com/linuxmint/muffin/commit/1d01e839d55239e5cad0a8498017b25079474c61)

```
Thread 1 (Thread 0x7f625599f140 (LWP 31875)):
#0  0x00007f6253babbf9 in __GI___poll (fds=0x7fff1f7a44f8, nfds=1, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
#1  0x00007f624d5ec747 in  () at /usr/lib/x86_64-linux-gnu/libxcb.so.1
#2  0x00007f624d5ee06f in  () at /usr/lib/x86_64-linux-gnu/libxcb.so.1
#3  0x00007f624d5ee1ef in xcb_wait_for_reply64 () at /usr/lib/x86_64-linux-gnu/libxcb.so.1
#4  0x00007f6254c356e8 in _XReply () at /usr/lib/x86_64-linux-gnu/libX11.so.6
#5  0x00007f6254c1b435 in XGetWindowProperty () at /usr/lib/x86_64-linux-gnu/libX11.so.6
#6  0x00007f62552ade91 in meta_background_actor_update (screen=screen@entry=0x5648f6cd2000 [MetaScreen]) at compositor/meta-background-actor.c:550
#7  0x00007f62552ac390 in process_property_notify (event=0x7fff1f7a4b30, event=0x7fff1f7a4b30, window=0x0, compositor=0x5648f703a0b0) at compositor/compositor.c:194
#8  0x00007f62552ac390 in meta_compositor_process_event (compositor=0x5648f703a0b0, event=event@entry=0x7fff1f7a4b30, window=window@entry=0x0) at compositor/compositor.c:878
#9  0x00007f62552c22fa in event_callback (event=0x7fff1f7a4b30, data=0x5648f6cfcf10) at core/display.c:2706
#10 0x00007f625530f068 in filter_func (xevent=0x7fff1f7a4b30, event=<optimized out>, data=<optimized out>) at ui/ui.c:243
#11 0x00007f6250b54eef in gdk_event_apply_filters (xevent=xevent@entry=0x7fff1f7a4b30, event=event@entry=0x5648f9274c90, window=window@entry=0x0) at ../../../../../gdk/x11/gdkeventsource.c:79
#12 0x00007f6250b551d9 in gdk_event_source_translate_event (xevent=0x7fff1f7a4b30, event_source=0x5648f6863070) at ../../../../../gdk/x11/gdkeventsource.c:198
#13 0x00007f6250b551d9 in _gdk_x11_display_queue_events (display=0x5648f684c000 [GdkX11Display]) at ../../../../../gdk/x11/gdkeventsource.c:341
#14 0x00007f6250b1fd70 in gdk_display_get_event (display=display@entry=0x5648f684c000 [GdkX11Display]) at ../../../../gdk/gdkdisplay.c:438
#15 0x00007f6250b54f82 in gdk_event_source_dispatch (source=source@entry=0x5648f6863070, callback=<optimized out>, user_data=<optimized out>) at ../../../../../gdk/x11/gdkeventsource.c:363
#16 0x00007f6254105417 in g_main_dispatch (context=0x5648f683a6b0) at ../../../../glib/gmain.c:3176
#17 0x00007f6254105417 in g_main_context_dispatch (context=context@entry=0x5648f683a6b0) at ../../../../glib/gmain.c:3829
#18 0x00007f6254105650 in g_main_context_iterate (context=0x5648f683a6b0, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at ../../../../glib/gmain.c:3902
#19 0x00007f6254105962 in g_main_loop_run (loop=0x5648f683bc20) at ../../../../glib/gmain.c:4098
#20 0x00007f62552cef94 in meta_run () at core/main.c:581
#21 0x00005648f5056a54 in main (argc=<optimized out>, argv=<optimized out>) at main.c:327
Detaching from program: /usr/bin/cinnamon, process 31875
```

**Comment by clefebvre** [comment]
Because iter-20 looked so stable when we tested it, I've made a comparison of the differences between iter-20 and current master. Here's what I found..

The picture belows show the commits which are in cinnamon master but not in iter-20:

![image (14)](https://user-images.githubusercontent.com/1138515/59190637-1fa74080-8b75-11e9-970a-7cd114f38f0a.png)

In bold are the commits which have a potential impact on the behaviour of Cinnamon.

On the muffin side, there are more differences:

![image (15)](https://user-images.githubusercontent.com/1138515/59190641-22099a80-8b75-11e9-890c-7d0e6e8ca191.png)

Again, in bold are the commits which can have an impact on the WM. Some are unlikely to have caused regressions, I indicated that beside them.

**Comment by jaszhix** [comment]
Just revert it all, there's no point in working on this when you concoct a giant cherry-picked branch, and we have to discover what all these issues are all over again. We had a chance to land this change set in 4.2 and I failed to do it on time. I don't think I want to see cinnamon worse than 4.0 in stability, so I recommend not applying these patches unless you're ready to revert your reverts and let me finish. There were a lot of issues with missing commits, builds not building, etc. I wrote most of these patches and you never once asked me for my feedback during the process.

**Comment by clefebvre** [comment]
"Glitch when choosing Fly Down in window effects dialog" is introduced by https://github.com/linuxmint/muffin/commit/8ce454463fc067cf1f95417f791166a64cc0bb52 (i.e. it's in 4.0-maintenance).

**Comment by jaszhix** [comment]
That PR also has other issues master didn't, like the restart segfault. That PR turned into much more than a simple fix for CSD windows disappearing, I ended up rebasing it on 4.2 code it shouldn't have been based on because it was open after we started merging for 4.2, but it was a bug fix for 4.0.

**Comment by clefebvre** [comment]
"Crash in meta_window_should_unredirect" might be fixed already (by https://github.com/linuxmint/muffin/commit/e2d4bd47d70add68e53165e62cd59b9273b7003b). It's introduced by https://github.com/linuxmint/muffin/commit/1d01e839d55239e5cad0a8498017b25079474c61.

**Comment by clefebvre** [comment]
"Freeze after entering password in screensaver (see below)" is hard to reproduce. It's likely to be introduced by https://github.com/linuxmint/muffin/commit/1d01e839d55239e5cad0a8498017b25079474c61 as well.

**Comment by jaszhix** [comment]
I closed linuxmint/muffin#510 for the screensaver bug, and you told me about an hour ago it's just a workaround you didn't like, so I closed it. Feel free to re-open it.

@leigh123linux has not reproduced the should_unredirect segfault since linuxmint/muffin#514.

**Comment by clefebvre** [comment]
I can reproduce the tooltip issue reliably. I'm bisecting it now... it's in master-5.6 but not in iter-20. I'll find the commit which introduces it.

**Comment by jaszhix** [comment]
I'll save you some time - it's probably the change to using global.focus_window for stack change in layoutManager. That changed because those functions are spammed every second on Nvidia. I can't reproduce so this is just a guess, but that file definitely is where any issues with tooltips have occurred.

**Comment by jaszhix** [comment]
Or, it's caused by using global.display.get_pointer.

**Comment by jaszhix** [comment]
Actually the latter sounds more correct, `cinnamon_global_sync_pointer` was added solely because of issues with clutter. I replaced a GDK call in that method that I stepped through in glib and discovered it's just calling `XQueryPointer` through several layers of abstraction. So I replaced it with our thin wrapper of that. That's all I know.

**Comment by clefebvre** [comment]
Confirmed, it's introduced by https://github.com/linuxmint/cinnamon/commit/74d14ea9cbb01849d46cda8673d668a6861e29b4.

**Comment by jaszhix** [comment]
More specifically, you just need to revert `cinnamon_global_sync_pointer ` to fix it.

**Comment by jaszhix** [comment]
Regardless if it's the signal change from `restacked` in layoutManager.js or that, it's worth pointing out the only thing that got me looking in that code and refactoring was a performance regression from https://github.com/linuxmint/cinnamon/pull/8351 on Nvidia that nobody could reproduce within the team. I botched the execution and it's unfortunate because those changes both recovered some responsiveness from that PR as a whole.

**Comment by jaszhix** [comment]
I just hope you see that telling me to not work on this is basically telling me you don't want me on the team. 

I can only use cinnamon on the patches you reverted last week. This is my way of preserving my ability to stay on the team, but to me it seems you think me questioning your decisions during the process is more dangerous to that. We'll never know which outcome was better, but I suspect it was the rare opportunity Linux Mint had a developer to sort out their compositor issues, temporarily full time, but to then reject them and get stale because we have to make an arbitrary release window. It turns out I was the only one really testing Nvidia (non-prime, no mesa) with multiple monitors for a while. 

I thought I was going to try to put them back for 4.4, but after your deflection of merging code that can't build into master, and not letting me fix even the aftermath of the revert, it probably won't.

**Comment by clefebvre** [comment]
@LinuxOnTheDesktop @JosephMcc @pizzadude, can you test this build:

[backtoiter-20.zip](https://github.com/linuxmint/alpha-testing/files/3272326/backtoiter-20.zip)

It's the combination of https://github.com/linuxmint/cinnamon/pull/8624 and https://github.com/linuxmint/muffin/pull/520.

It should fix:

- Stuck tooltips
- Screensaver issues

And ensure we don't bump into the following issues:

- Input region issues
- should_unredirect crash

^^ believed to be fixed but we're not sure 100%.

**Comment by clefebvre** [comment]
@brownsr I couldn't reproduce the artefacts in window list so I couldn't bisect it unfortunately.

**Comment by clefebvre** [comment]
@JosephMcc I can't really reproduce the input region issue in slack (when minimizing it and restoring it from tray, if you can still reproduce it, let me know if backtoiter-20.zip fixes it).

**Comment by clefebvre** [comment]
The flydown effect issue is caused by https://github.com/jaszhix/muffin/commit/3ec19b06aaa11be8861ea50088d650f78cd0d92a. We should revert this as well, both on master and 4.0-maintenance.

**Comment by jaszhix** [comment]
Please point to commits on your remote, not mine.

**Comment by jaszhix** [comment]
Also, I tried to leave the team but it wouldn't let me. Please remove me from the organization.

**Comment by clefebvre** [comment]
OK, that commit doesn't exist on its own here Jason.

**Comment by jaszhix** [comment]
Check the PRS, they exist on a hidden branch

**Comment by clefebvre** [comment]
Done.

**Comment by jaszhix** [comment]
I got the email notification. Also, please don't ping me anymore. Speaking to everyone on the team. I've sacrificed enough of my career for Linux Mint.

**Comment by JosephMcc** [comment]
Using backtoiter-20 I can no longer reproduce the stuck tooltip or slack issues. At first try the screensaver also seems to be working properly.

**Comment by jaszhix** [comment]
That tends to happen when you revert everything. Lose nothing, gain nothing.

**Comment by clefebvre** [comment]
@JosephMcc how about the stuck notifications?

**Comment by JosephMcc** [comment]
@clefebvre I have experienced the stuck notifications on the build. Still do not know the trigger and it doesn't always happen. Will need a bit of time to be sure.

**Comment by LinuxOnTheDesktop** [comment]
@clefebvre 

Using the build you provided, I no longer see any problem with tooltips. Also, the lock screen now accepts input, but, unfortunately, it takes too long - about a second, with some visual artefacting - to unlock the computer.

**Comment by clefebvre** [comment]
It takes longer than when...? You mean after you enter the password? and what artefacts do you see?

PS: You're getting updates from the PPA because the build I gave you is an inferior version, so mintupdate is putting you back to PPA version.

**Comment by LinuxOnTheDesktop** [comment]
Sorry: I could have explained more fully there. I meant: there is a delay of approximately one second between (i) entering the correct password and (ii) seeing the desktop. That said, in between i and ii I see the desktop, briefly, with, I think, the lockscreen superimposed upon it.

**Comment by pizzadude** [comment]
@clefebvre The laggy lockscreen bug seems to be fixed. I didn't notice any artifacting with regards to the screensaver.

@LinuxOnTheDesktop if you are testing this build, don't update cinnamon unless you want to go back to the PPA build

**Comment by JosephMcc** [comment]
@LinuxOnTheDesktop Also please be sure to restart your machine after you install the new ones. Just to be sure you are on a clean setup.

**Comment by LinuxOnTheDesktop** [comment]
@JosephMcc 

I thought that I had restarted. But I restarted again and suspended twice (both times for brief periods) and on the first occasion there was no problem and on the second there was a delay of approximately one second before I saw the desktop but this time I noticed not artefacts. It's possible something on my system is causing or helping to cause the problem; can you reproduce the problem?

**Comment by pizzadude** [comment]
I forgot to mention, there's also this issue when scrolling down the "Games" and "All applications" category of my application list, and while searching. It only happens on certain themes, like the "Linux Mint" default theme, and the CBlue theme. It's not a big deal though. (I don't want to increase more burden on the developers)

![Peek 2019-06-10 13-17](https://user-images.githubusercontent.com/1454420/59213282-7e26eb80-8b82-11e9-81fc-274db96779ee.gif)

**Comment by JosephMcc** [comment]
@LinuxOnTheDesktop Do you only get this when using suspend? Or does it happen without that also. On my personal machines, suspend in general on Linux seems to be a little hit and miss on how well it works. On my all intel laptop it works great but on the Nvidia machine it often doesn't.

**Comment by JosephMcc** [comment]
@pizzadude I'm getting something similar to you though not quite the same using the "Linux Mint" theme.

**Comment by LinuxOnTheDesktop** [comment]
@JosephMcc 

I am using a laptop with Intel graphics. I have not encountered any unexpected delays or visual artefacts when doing anything else on the build Clem supplied. Still, I've only been running that build for a few hours and I haven't done much on that computer. (I type this from another computer.) Also: Mint 19.1 Cinnamon stable didn't have the problems.

**Comment by JosephMcc** [comment]
@LinuxOnTheDesktop Thanks for the additional feedback

**Comment by brownsr** [comment]
@clefebvre the artifacting is not on the window list, but on individual applets.  In fact I have only managed to see it on a couple of themes (Linux Mint, and Divo).  In the Linux Mint theme I have only seen it on the menu and desktop applets. It's intermittent too. I've just noticed a couple of other things along the way, will rebuild and check first.

**Comment by brownsr** [comment]
As far as I can tell this one is specific to Opera (current version from the Opera web site).  Launch it fullscreen then minimise.  Now restart Cinnamon.  I have the backgrounds set to cycle so it comes up with a different background.  The hover thumbnail in the grouped window list will show the old background, and the preview of that will show it over the whole screen to make it more obvious.  It can be a bit mangled as well, doubled up or torn, that seems to vary.
![Screenshot from 2019-06-10 20-34-58](https://user-images.githubusercontent.com/6322481/59222714-0e385580-8bc2-11e9-8c56-2a46779dc88a.png)

**Comment by pizzadude** [comment]
I thought should be worth mentioning that the artifacting showed in the gif I posted earlier today isn't always as severe, as shown in this gif:

![Peek 2019-06-10 23-08](https://user-images.githubusercontent.com/1454420/59241281-09c96800-8bd5-11e9-9f0d-057022b4956d.gif)

**Comment by clefebvre** [comment]
Thanks guys. We found the source of the icon artefacts.

**Comment by clefebvre** [comment]
icons artefacts (and shadows afaik) are fixed on master with https://github.com/linuxmint/cinnamon/commit/d7c6da51a062b95bfeedd951224ac1779c32d9e9.

**Comment by pizzadude** [comment]
Icon artifacting confirmed fixed.

**Comment by clefebvre** [comment]
The PPA is up to date.

**Comment by LinuxOnTheDesktop** [comment]
I am not seeing the stuck tooltips anymore. I am on the latest PPA build.
